name: Continuous integration
on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      influxdb:
        image: influxdb:2.0.4-alpine
        ports: ["8086:8086"]
        env:
          INFLUXD_HTTP_BIND_ADDRESS: :8086
      postgres:
        image: postgres:13-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres

    env:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      RAILS_ENV: test
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      DISABLE_SPRING: 1

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Lint with RuboCop
        run: bundle exec rubocop --parallel

      - name: Lint with SlimLint
        run: bundle exec slim-lint .

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn packages
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Yarn packages
        run: yarn install --frozen-lockfile

      - name: Setup InfluxDB
        run: bin/influxdb-onboarding.sh

      - name: Setup PostgreSQL
        run: bin/rails db:create

      - name: Compile assets
        run: bin/rails webpacker:compile

      - name: Run Tests
        run: bin/rspec

      - name: Send test coverage to CodeClimate
        uses: paambaati/codeclimate-action@v2.7.5
        with:
          coverageCommand: true

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Screenshots
          path: tmp/screenshots

  deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT2 }}

      - name: Build the production image
        run: |
          export COMMIT_TIME=$(git show -s --format=%ci ${GITHUB_SHA})
          export COMMIT_SHA=${GITHUB_SHA}
          docker build --build-arg COMMIT_TIME --build-arg COMMIT_SHA -t app .

      - name: Push the image tagged as DEVELOP to the container registry
        if: github.ref == 'refs/heads/develop'
        run: |
          docker tag app ghcr.io/${{ github.repository_owner }}/solectrus:develop
          docker push ghcr.io/${{ github.repository_owner }}/solectrus:develop

      - name: Push the image tagged as LATEST to the container registry
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag app ghcr.io/${{ github.repository_owner }}/solectrus:latest
          docker push ghcr.io/${{ github.repository_owner }}/solectrus:latest

      - name: Push the image tagged with version to the container registry
        if: startsWith(github.ref, 'refs/tags')
        run: |
          docker tag app ghcr.io/${{ github.repository_owner }}/solectrus:${GITHUB_REF/refs\/tags\//}
          docker push ghcr.io/${{ github.repository_owner }}/solectrus:${GITHUB_REF/refs\/tags\//}

      - name: Send notification
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
